import type { ReactNode } from "react";
import { HeadContent, Outlet, Scripts, createRootRoute } from "@tanstack/react-router";
import { NotFound } from "@/pages/not-found";
import { RouteProvider } from "@/providers/router-provider";
import { ThemeProvider } from "@/providers/theme-provider";
import appCss from "@/styles/globals.css?url";

export const Route = createRootRoute({
    head: () => ({
        meta: [
            { charSet: "utf-8" },
            { name: "viewport", content: "width=device-width, initial-scale=1.0" },
            { name: "description", content: "Generated by Untitled UI CLI" },
            { name: "theme-color", content: "#7f56d9" },
            { title: "Starter kit — Untitled UI" },
        ],
        links: [
            { rel: "icon", type: "image/png", href: "/favicon.png" },
            { rel: "preconnect", href: "https://fonts.googleapis.com" },
            { rel: "preconnect", href: "https://fonts.gstatic.com", crossOrigin: "anonymous" },
            {
                rel: "stylesheet",
                href: "https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,400..700;1,14..32,400..700&display=swap",
            },
            { rel: "stylesheet", href: appCss },
        ],
        scripts: [
            {
                // On page load or when changing themes, best to run inline in `head` to avoid FOUC.
                children: `if (localStorage.theme === "dark" || (!("theme" in localStorage) && window.matchMedia("(prefers-color-scheme: dark)").matches)) { document.documentElement.classList.add("dark-mode"); } else { document.documentElement.classList.remove("dark-mode"); }`,
            },
        ],
    }),
    shellComponent: RootDocument,
    component: RootComponent,
    notFoundComponent: NotFound,
});

function RootDocument({ children }: { children: ReactNode }) {
    return (
        <html lang="en">
            <head>
                <HeadContent />
            </head>
            <body className="size-full bg-primary antialiased">
                {children}
                <Scripts />
            </body>
        </html>
    );
}

function RootComponent() {
    return (
        <ThemeProvider>
            <RouteProvider>
                <Outlet />
            </RouteProvider>
        </ThemeProvider>
    );
}
